### ISSUE TITLE
Rework changelog format to stop Twitch/CF from messing up the published notes

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#118]
They really are not very consistent. Markdown/HTML is rendered and displayed differently on all platforms...

- [x] GitHub releases: Looks OK, if not ideal due to a duplicate heading - I doubt anyone cares, though
- [x] Overwolf app: CF doesn't show changelogs
- [x] WowUp: Website - looks good to me - app doesn't show changelogs
- [x] CurseForge: Readable, although a bit awkward
- [x] WowAce: Looks OK

**Comment by SacredDuckwhale** [comment]
It appears no matter which format I use, it will be messed up in at least one of the channels... In order to make it manageable, I think some limitations should be put in place:

* The Curse/WowAce project site view is deemed irrelevant, as it breaks most often and isn't something most users would actually visit. Example: https://www.wowace.com/projects/rarity/files/3227299 (That's them choking on basic markdown syntax...)
* Change logs displayed on the main project site should probably be rendered correctly. I think it mostly uses the same logic, but apparently it's not quite identical (sigh). Example: https://www.curseforge.com/wow/addons/rarity/files
* The Twitch app/Overwolf app (or whatever official way there exists now) will be ignored, as wowup.io seems a much better (and open source) alternative. It doesn't currently display change logs, but if it ever does they should also be rendered correctly
* Formatting should ideally be limited to the subset available in Discord channels (no headings/HTML), so that they can be copy/pasted in without having to manually change anything

**Comment by Duckwhale** [comment]
On the topic of Discord changelog, it seems that this could (and should) be automated: Whenever a release is created, a bot (or webhook) could post the changelog from GitHub's release. They at least support proper Markdown formatting in every case.

**Comment by Duckwhale** [comment]
Discord changelogs have been disabled, until automation is set up for them.

**Comment by Duckwhale** [comment]
It looks like this problem has solved itself. CF still isn't great about honoring markdown, but it's readable at least...
