### ISSUE TITLE
Add tracking for 9.1 pets

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#355]
Should probably be tracked:

- [ ] https://www.wowhead.com/item=186555/eye-of-extermination
- [ ] https://www.wowhead.com/item=186554/eye-of-allseeing
- [ ] https://www.wowhead.com/item=186541/mosscoated-hopper
- [ ] https://www.wowhead.com/item=186552/rook
- [ ] https://www.wowhead.com/item=186558/irongrasp
- [ ] https://www.wowhead.com/item=186557/fodder
- [ ] https://www.wowhead.com/item=186550/mawsworn-minion
- [ ] https://www.wowhead.com/item=186449/amaranthine-stinger
- [ ] https://www.wowhead.com/item=186534/gizmo
- [ ] https://www.wowhead.com/item=186547/invasive-buzzer
- [ ] https://www.wowhead.com/item=186564/golden-eye
- [ ] https://www.wowhead.com/item=186546/copperback-etherwyrm
- [ ] https://www.wowhead.com/item=184867/squibbles
- [ ] https://www.wowhead.com/item=186549/gilded-darknight
- [ ] https://www.wowhead.com/item=186538/gnashtooth
- [ ] https://www.wowhead.com/item=186559/grappling-gauntlet
- [ ] https://www.wowhead.com/item=186542/korthian-specimen

TBD:

- [ ] https://www.wowhead.com/item=186544/sinfall-screecher
- [ ] https://www.wowhead.com/item=186540/rarity (this name is a coincidence, right?)

**Comment by kbuczynski-nashpl** [comment]
@Duckwhale full list of pets in 9.1 from the database
```
Pets 9.1
Damp Skrat - https://www.wowhead.com/npc=179167/damp-skrat
Turquoise Baubleworm - https://www.wowhead.com/npc=179138/turquoise-baubleworm
Fodder - https://www.wowhead.com/npc=179171/fodder
Scavenging Skrat - https://www.wowhead.com/npc=179168/scavenging-skrat
Eye of Allseeing - https://www.wowhead.com/npc=179232/eye-of-allseeing
Irongrasp - https://www.wowhead.com/npc=179222/irongrasp
Silver Purrkin - https://www.wowhead.com/npc=179165/silver-purrkin
Chompy - https://www.wowhead.com/npc=179230/chompy
Gilded Darknight - https://www.wowhead.com/npc=179239/gilded-darknight
Eve of Extermiantion - https://www.wowhead.com/npc=179233/eye-of-extermination
Copperback Etherwyrm - https://www.wowhead.com/npc=179132/copperback-etherwyrm
Amaranthine Stinger - https://www.wowhead.com/npc=179181/amaranthine-stinger
Curious Purrkin - https://www.wowhead.com/npc=179164/curious-purrkin
Squibbles - https://www.wowhead.com/npc=176662/squibbles
Churro - https://www.wowhead.com/npc=176658/churro
RT-3 M15 - https://www.wowhead.com/npc=176657/rt-3-m15
Deathroach - https://www.wowhead.com/npc=179226/deathroach
Invasive Buzzer - https://www.wowhead.com/npc=179180/invasive-buzzer
Gizmo - https://www.wowhead.com/npc=179166/gizmo
Topaz Baubleworm - https://www.wowhead.com/npc=179139/topaz-baubleworm
Gnashtooth - https://www.wowhead.com/npc=179255/gnashtooth
Mawsworn Minion - https://www.wowhead.com/npc=179240/mawsworn-minion
Rook - https://www.wowhead.com/npc=179242/rook
Animite Boordling - https://www.wowhead.com/npc=179131/animite-broodling
Scurrying Mawrat - https://www.wowhead.com/npc=179182/scurrying-mawrat
Lost Limb - https://www.wowhead.com/npc=179183/lost-limb
Domestic Aunian - https://www.wowhead.com/npc=179253/domestic-aunian
Sly - https://www.wowhead.com/npc=179083/sly
Wild Corpsefly - https://www.wowhead.com/npc=179329/wild-corpsefly
Anxious Nibbler - https://www.wowhead.com/npc=179248/anxious-nibbler
Young Garnetgullet - https://www.wowhead.com/npc=179250/young-garnetgullet
Clinging Remains - https://www.wowhead.com/npc=179179/clinging-remains
Devourling - https://www.wowhead.com/npc=179256/devourling
Timless Mechanical Dragonling - https://www.wowhead.com/npc=179125/timeless-mechanical-dragonling
Vile Deathroach - https://www.wowhead.com/npc=179227/vile-deathroach
Eye of Affliction - https://www.wowhead.com/npc=179229/eye-of-affliction
Grip of Terror - https://www.wowhead.com/npc=179219/grip-of-terror
Grappling Gauntlet - https://www.wowhead.com/npc=179220/grappling-gauntlet
Korthia Specimen - https://www.wowhead.com/npc=179251/korthian-specimen
Mosscoated Gromit - https://www.wowhead.com/npc=179252/mosscoated-gromit
Mord’al Eveningstar - https://www.wowhead.com/npc=179241/mordal-eveningstar
Flawless Amethyst Baubleworm - https://www.wowhead.com/npc=178216/flawless-amethyst-baubleworm
Lil’Abom - https://www.wowhead.com/npc=179008/lilabom
Infused Etherwyrm - https://www.wowhead.com/npc=179025/infused-etherwyrm
```

**Comment by godejord** [comment]
> Should probably be tracked:

> * [ ]  https://www.wowhead.com/item=187075/box-of-rattling-chains

This is a toy, so just listed in the wrong place.

**Comment by Duckwhale** [comment]
The ones available from assaults have been moved to separate issues; as such this one can be closed already.
