### ISSUE TITLE
Add tracking for (the first batch of) 9.1 toys

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#356]
These are the toys we can safely assume are worth tracking with the currently very limited data available:

- [x] https://www.wowhead.com/item=187176/vesper-of-harmony
- [x] https://www.wowhead.com/item=183901/bonestorm-top
- [x] https://www.wowhead.com/item=187185/vesper-of-faith
- [x] https://www.wowhead.com/item=187139/bottled-shade-heart
- [x] https://www.wowhead.com/item=187420/maw-ocular-viewfinder

Moved to separate issues, due to lack of data/details on their availability:

- https://www.wowhead.com/item=187075/box-of-rattling-chains (https://github.com/WowRarity/Rarity/issues/358)
- https://www.wowhead.com/item=187113/personal-ball-and-chain (https://github.com/WowRarity/Rarity/issues/361)
- https://www.wowhead.com/item=187416/jailers-cage (https://github.com/WowRarity/Rarity/issues/361)
- https://www.wowhead.com/item=187417/adamant-vaults-cell (https://github.com/WowRarity/Rarity/issues/360)
- https://www.wowhead.com/item=187174/shaded-judgment-stone (https://github.com/WowRarity/Rarity/issues/359)

**Comment by kbuczynski-nashpl** [comment]
### Toys 9.1

Forgotten Feather - https://www.wowhead.com/item=187051/forgotten-feather
Ancient Korthain Runes - https://www.wowhead.com/item=187154/ancient-korthian-runes
Offering Kit Maker - https://www.wowhead.com/item=187344/offering-kit-maker
Silver Shardhide Whistle - https://www.wowhead.com/item=187339/silver-shardhide-whistle
Experimental Anima Cell - https://www.wowhead.com/item=186974/experimental-anima-cell
Maw-Ocular Viewfinder - https://www.wowhead.com/item=187420/maw-ocular-viewfinder
Anima-ted Leash - https://www.wowhead.com/item=186973/anima-ted-leash
Bottled Shade Heart - https://www.wowhead.com/item=187139/bottled-shade-heart
Shaded Judgment Stone - https://www.wowhead.com/item=187174/shaded-judgment-stone
Ring of Duplicity - https://www.wowhead.com/item=187140/ring-of-duplicity
Guise of the Changeling - https://www.wowhead.com/item=187155/guise-of-the-changeling
Jailer’s Cage - https://www.wowhead.com/item=187416/jailers-cage
Elusive Pet Treat - https://www.wowhead.com/item=186985/elusive-pet-treat
Shadow Slicing Shortsword - https://www.wowhead.com/item=187159/shadow-slicing-shortsword
Pallid Oracle Bones - https://www.wowhead.com/item=186686/pallid-oracle-bones
Doomwalker Trophy Stand - https://www.wowhead.com/item=186501/doomwalker-trophy-stand
Adamant Vaults Cell - https://www.wowhead.com/item=187417/adamant-vaults-cell
Pallid Bone Flute - https://www.wowhead.com/item=186702/pallid-bone-flute
Vesper of Faith - https://www.wowhead.com/item=187185/vesper-of-faith
Personal Ball and Chain - https://www.wowhead.com/item=187113/personal-ball-and-chain
Bonestorm Top - https://www.wowhead.com/item=183901/bonestorm-top
Box of Rattling Chains - https://www.wowhead.com/item=187075/box-of-rattling-chains
Vesper of Harmony - https://www.wowhead.com/item=187176/vesper-of-harmony
Vesper of Clarity - https://www.wowhead.com/item=187184/vesper-of-clarity
