### ISSUE TITLE
Add GitHub Actions workflow to enforce consistent formatting across all files when a PR is updated

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#386]
Goals:

- [x] Before merging in any changes, we want to make sure the formatting is consistent everywhere (see #331)
- [x] When changes have been made to legacy files, the CI will notify us of the inconsistency, so that it can be fixed separately (if unrelated to the PR)
- [x] If this requires elaborate setup, like installing ``luarocks``, it could be easier to just do it after running ``luacheck`` (for every commit?)

Roadmap:

- [x] Research what CLI commands need to be run
- [x] Update the ``luacheck.yaml`` workflow OR create a separate ``luaformat.yaml`` one (TBD)
