### ISSUE TITLE
Re-add separate tracking for BFA Challenge Mode dungeons (Mythic Plus)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#52]
Related to #51 - after Mythic Plus is released for BFA, this can be tackled. Can probably use the scenario tracking system from Island Expeditions (see #49)?

---

Roadmap:
- [ ] Research: Is the drop rate the same as from regular Mythic dungeons?
- [ ] Research: Does it change with difficulty levels? (Higher keys = higher drop chance or something)
- [x] Feature: Mythic Keystone detection
- [ ] Testing: Verify challenge mode completion tracking is working as intended
- [ ] Testing: Verify attempts being added for all relevant items

---

Milosh tested the detection and it seems to be working. I can't speak to differences in drop rates and I doubt there is sufficient data to support any such assumption, so this will have to suffice.

**Update:**  The detection based on statistics counting is currently active, but doesn't seem to be working correctly for some dungeons (see #68). This feature is put on hold until it's become clear whether or not the separate CM detection is actually needed. If statistics tracking can be fixed and isn't broken on Blizzard's end, it may become obsolete.

**Comment by SacredDuckwhale** [comment]
Waiting to see what the deal is with the statistics tracking (#68).

**Comment by SacredDuckwhale** [comment]
I can't look into Mythic plus as it requires extensive testing, and I lack the time. This'll have to wait :(

**Comment by Duckwhale** [comment]
Obsolete.
