### ISSUE TITLE
Add support for tracking drops from Time Rift event bosses (in addition to tracking their container items)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#579]
It might be possible to do this with some custom (hacky) glue code, or by supporting multiple item sources (tricky).

Roadmap:

- [x] Add the missing collectibles to the database (since they seem to also drop from the rifts)
- [x] Collect the required achievement criteria IDs (see Discord)
- [x] Add event handling logic for these criteria

---

Follow-up from #566 - the PR only added tracking via container, but kills can also drop the items (according to wowhead reports).

**Comment by Duckwhale** [comment]
It looks like there are seven different scenarios that could be tracked (Source: [wowhead](https://www.wowhead.com/guide/time-rifts-dragonflight#phase-2-alternate-realities)).

TBD:

* Does every final boss in every scenario drop all of the mounts? If so, we can just track the scenario completions (I think)
* What events can be used to track these? Maybe `ENCOUNTER_END` or `SCENARIO_COMPLETED`, or even `QUEST_TURNED_IN`?
* What IDs (encounter, quest, or otherwise) are used for the rifts? I haven't found anything on wowhead or in the DBC data

It might be necessary to run through all the rifts with `/etrace` to gather more info, but that seems fairly involved.

**Comment by Duckwhale** [comment]
UI map IDs:

![image](https://github.com/WowRarity/Rarity/assets/16489133/9cb27cbe-1e72-471c-945f-fad1872cf954)

The rifts themselves can be tracked via achievement criteria, same as Timewalking. But I haven't found any IDs online.

Assuming there's only seven different rifts (one boss per "world", i.e., no variations)... this might be a starting point:

* 60690 = Azewrath = Illidan Stormrage
* 60691 = Azq'roth = Fury of N'zoth

I'm guessing the others are close (60692 etc.) but there's no API AFAIK so I can't say for sure.

**Comment by cyriun** [comment]
> It looks like there are seven different scenarios that could be tracked (Source: [wowhead](https://www.wowhead.com/guide/time-rifts-dragonflight#phase-2-alternate-realities)).
> 
> TBD:
> 
> * Does every final boss in every scenario drop all of the mounts? If so, we can just track the scenario completions (I think)
> * What events can be used to track these? Maybe `ENCOUNTER_END` or `SCENARIO_COMPLETED`, or even `QUEST_TURNED_IN`?
> * What IDs (encounter, quest, or otherwise) are used for the rifts? I haven't found anything on wowhead or in the DBC data
> 
> It might be necessary to run through all the rifts with `/etrace` to gather more info, but that seems fairly involved.

not sure if you had any different but all i seen in my event log was SCENARIO_COMPLETED = nil

**Comment by Duckwhale** [comment]
That comment is outdated, we can use the existing detection for Timewalking (achievement criteria - see Discord). I'm on it :)

**Comment by cyriun** [comment]
gotcha, the mechagon one is 60693 btw. i had internet issues during it and only caught it on etrace
