### ISSUE TITLE
Tracking for the Horseman's Reins isn't working after the 2023 changes to Hallow's End

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#664]
Source: [Discord](https://discord.com/channels/788119147740790854/788119800617369611/1164199807737397299)
> The horsemans reins are not tracked on this years event
> I think the ID's of things changed which might be why it's not picking it up 

![image](https://github.com/WowRarity/Rarity/assets/16489133/f83be85a-34df-4e78-90d8-5be3cacc2b92)

Roadmap:

- [ ] Verify the new container ID (if possible)
- [ ] Add it to the database
- [ ] TBD: Should the old container be removed?
