### ISSUE TITLE
Add tracking for rare achievements in The War Within zones

### ISSUE THREAD

**Issue by rdw-software** [WowRarity/Rarity#747]
Not sure how many people make use of this feature, but it's been traditionally something Rarity tracks for each expansion.

Roadmap:

- [x] Add achievement-related NPCs in the Options module
  - [x] https://www.wowhead.com/achievement=40435/adventurer-of-the-isle-of-dorn
  - [x] https://www.wowhead.com/achievement=40837/adventurer-of-the-ringing-deeps
  - [x] https://www.wowhead.com/achievement=40840/adventurer-of-azj-kahet
  - [x] https://www.wowhead.com/achievement=40851/adventurer-of-hallowfall
