### ISSUE TITLE
Add tracking for the 20th anniversary world bosses

### ISSUE THREAD

**Issue by rdw-software** [WowRarity/Rarity#784]
Source: [Discord](https://discord.com/channels/788119147740790854/788119314909626388/1299069721471090789)
> Any chance the mounts from the 20th anniversary world bosses will be added?

Source: [Curse](https://www.wowace.com/projects/rarity?comment=3076)
> Is there any way we could get an update for the bosses at the anniversary event to show for tracking mount drops? 

The event is going to last until January, but only the Doomwalker drops seem to be updated. 2/3 drop their usual mount.

Roadmap:

- [ ] [Doomwalker](https://www.wowhead.com/npc=167749)
  - [ ] [Illidari Doomhawk](https://www.wowhead.com/item=186469): Used to be guaranteed, now rare again? Can also be purchased at the vendor, though?
  - [ ] [Azure Worldchiller](https://www.wowhead.com/item=208572): Same... now listed with a 1.5% chance on wowhead
  - [ ] [Reins of the Grand Black War Mammoth](https://www.wowhead.com/item=43959): Now also drops from Doomwalker, for... reasons?
    - [ ] TBD: Can this even be added when Rarity only supports a single source per item?
- [ ] [Sha of Anger](https://www.wowhead.com/npc=226646): Reins of the Heavenly Onyx Cloud Serpent
  - [ ] TBD: Does killing the anniversary version also update the kill statistic? If not, need to find a workaround
- [ ] [Archavon the Stone Watcher](https://www.wowhead.com/npc=227257): Reins of the Grand Black War Mammoth
  - [ ] TBD: Same issue with kill statistics?
  - [ ] TBD: Is it a problem that there are two (faction-specific) versions?
- [ ] Add `wasGuaranteed = true` flag where needed
- [ ] Add `sourceText` property for the vendor mounts
- [ ] Add the daily lockout quest

```lua
local lootLockoutQuests = {
  Doomwalker = 60214,
  Archavon = 84256,
  Sha = 84282
}
```

For more info, see the [wowhead guide](https://worldofwarcraft.blizzard.com/en-us/news/24147266/the-world-of-warcraft-20th-anniversary-celebration-update-is-now-live) and [this wowhead post](https://www.wowhead.com/news/rewarding-threats-of-the-past-anniversary-world-bosses-will-drop-mounts-347156#news-post-347156).

**Comment by rdw-software** [comment]
Did some research (reading wowhead guides/comments mostly). AFAICT, the elephant in the room here is that Rarity still only supports one source per item. This may be problematic as Doomwalker shares the mammoth. Maybe there's a workaround?

For Sha and Archavon, the most important question is whether they use the same kill statistic. If not, that's another headache?

**Comment by rdw-software** [comment]
Nope, statistics aren't used. The loot method is also problematic. `NPC` won't work and `BOSS` may trigger false positives.

**Comment by rdw-software** [comment]
Seeing how the anniversary is now over, this has become obsolete. Too bad, but maybe the event will return in the future.
